spring:
  profiles:
    active: dev
---
server:
   port: 8201
spring:
  profiles: dev             # 开发环境
  application: 
    name: pan-config-client
eureka: 
   client: 
      service-url: 
         defaultZone: http://enreka-dev.com:7001/eureka/
---
server:
   port: 8202
spring:
  profiles: test             # 测试环境
  application: 
    name: pan-config-client
eureka: 
   client: 
      service-url: 
         defaultZone: http://enreka-dev.com:7001/eureka/
---
# 请保存为UTF-8格式，不然上传到git会有乱码
# 请保存为UTF-8格式，不然上传到git会有乱码
# 请保存为UTF-8格式，不然上传到git会有乱码